// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtmZERowuCblczIjY_03rMAhBYzfhaGv0',
    appId: '1:124248305271:web:cad39a8d5c015307ab6072',
    messagingSenderId: '124248305271',
    projectId: 'hairstylr-d528b',
    authDomain: 'hairstylr-d528b.firebaseapp.com',
    storageBucket: 'hairstylr-d528b.firebasestorage.app',
    measurementId: 'G-LQEYM2XVEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQcQpp2IK53w7wtLOfsoX_saszcf62A8',
    appId: '1:124248305271:android:e34614bdb8cf25ddab6072',
    messagingSenderId: '124248305271',
    projectId: 'hairstylr-d528b',
    storageBucket: 'hairstylr-d528b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARcSnqwqsLPKtu898ek0kEpRioU0HMATU',
    appId: '1:124248305271:ios:2040817522ad6703ab6072',
    messagingSenderId: '124248305271',
    projectId: 'hairstylr-d528b',
    storageBucket: 'hairstylr-d528b.firebasestorage.app',
    iosBundleId: 'com.example.hairstylr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARcSnqwqsLPKtu898ek0kEpRioU0HMATU',
    appId: '1:124248305271:ios:2040817522ad6703ab6072',
    messagingSenderId: '124248305271',
    projectId: 'hairstylr-d528b',
    storageBucket: 'hairstylr-d528b.firebasestorage.app',
    iosBundleId: 'com.example.hairstylr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtmZERowuCblczIjY_03rMAhBYzfhaGv0',
    appId: '1:124248305271:web:96ae47b5792f599fab6072',
    messagingSenderId: '124248305271',
    projectId: 'hairstylr-d528b',
    authDomain: 'hairstylr-d528b.firebaseapp.com',
    storageBucket: 'hairstylr-d528b.firebasestorage.app',
    measurementId: 'G-D55G7EFK56',
  );
}
